platform :ios, '8.0'

target 'MyProject' do

pod 'AFNetworking', '~> 3.0'
pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'TZImagePickerController'
pod 'UIActionSheet+Blocks'
pod 'UIAlertView+Blocks'
pod 'WZLBadge'
pod 'SVProgressHUD'
pod 'UTDID'
pod 'MJExtension'
pod 'WMPageController'
pod 'XHLaunchAd'
end
